### ISSUE TITLE
Welcome to SEBC!

### ISSUE THREAD

**Issue by mfernest** [msmarnaoui/SEBC#1]
Your setup needs a few elements to be complete and correct:
* Please invite `rsiwicki` to collaborate on your repo, if you have not already.
* You're missing the `incomplete` label, and possibly others -- please check this work
* You have not yet set milestones for Labs and Challenges

Once you cleared all these matters, you can remove the `invalid` label and close this Issue.

Good luck this week!

**Comment by msmarnaoui** [comment]
done
